---
- name: Check if zsh is installed
  command: zsh --version
  register: zsh_installed
  ignore_errors: true
  changed_when: false

- name: Install zsh based on OS
  include_tasks: "{{ os_family }}.yml"