---
- name: Check if delta is installed
  command: delta --version
  register: delta_installed
  ignore_errors: true
  changed_when: false

- name: Install delta based on OS
  include_tasks: "{{ os_family }}.yml"

- name: Common tasks
  include_tasks: "common.yml"