gui:
  border: 'rounded'
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - bold
    searchingActiveBorderColor:
      - '#55583A'
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - '#5A5A5A'
    selectedRangeBgColor:
      - '#5A5A5A'
    cherryPickedCommitBgColor:
      - '#EDB6A3'
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
 - key: 'A'
   context: 'files'
   command: "$HOME/dotfiles/tools/lazygit-custom-amment-commit.sh"
   subprocess: true
   description: 'Run the script to amment the last commit'
 - key: 'c'
   context: 'files'
   command: "$HOME/dotfiles/tools/lazygit-custom-commit-workflow.sh"
   subprocess: true
   description: 'Run the script to create a commit'
 - key: '<c-c>'
   context: 'files'
   command: "$HOME/dotfiles/tools/lazygit-custom-submodule-commit-workflow.sh"
   subprocess: true
   description: 'Run the script to create a commit current repository and parent repository'
 - key: 'c'
   context: 'commits'
   command: " echo '{{ .SelectedCommit.Sha }}' | $HOME/dotfiles/tools/lazygit-custom-submodule-pick-commit-workflow.sh"
   subprocess: true
   description: 'Run the script to create a commit in the parent directory (submodule)'
