git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
 - key: 'c'
   context: 'files'
   command: "~/git_commit.sh"
   subprocess: true
   description: 'Run the tool to create a commit'
