os:
  editPreset: 'nvim'
gui:
  border: 'rounded'
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - bold
    searchingActiveBorderColor:
      - '#55583A'
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - '#5A5A5A'
    selectedRangeBgColor:
      - '#5A5A5A'
    cherryPickedCommitBgColor:
      - '#EDB6A3'
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  merging:
    manualCommit: false
    args: "--no-ff"
  mainBranches:
    - master
    - main
    - 18.0
    - 17.0
    - 18.0-develop
  overrideGpg: true
customCommands:
  - key: 'A'
    context: 'files'
    command: "$HOME/dotfiles/tools/lazygit-custom-amment-commit.sh"
    description: 'Run the script to amment the last commit'
    output: terminal
  - key: 'c'
    context: 'files'
    command: "$HOME/dotfiles/tools/lazygit-custom-commit-workflow.sh"
    description: 'Run the script to create a commit'
    output: terminal
  - key: '<c-c>'
    context: 'files'
    command: "$HOME/dotfiles/tools/lazygit-custom-submodule-commit-workflow.sh"
    description: 'Run the script to create a commit current repository and parent repository'
    output: terminal
  - key: 'c'
    context: 'commits'
    command: " echo '{{ .SelectedCommit.Sha }}' | $HOME/dotfiles/tools/lazygit-custom-submodule-pick-commit-workflow.sh"
    description: 'Run the script to create a commit in the parent directory (submodule)'
    output: terminal
  - key: 'U'
    context: 'localBranches'
    command: "echo '{{ .SelectedLocalBranch.Name }}' | $HOME/dotfiles/tools/lazygit-custom-upstream-workflow.sh"
    description: 'Run the script to create an upstream/push to a specific remote of the selected branch'
    output: terminal
  - key: '<c-c>'
    context: 'commits'
    command: "$HOME/.local/bin/commitcraft -r"
    description: 'Run CommitCraft in Relesse mode'
    output: terminal
  - key: 'R'
    context: 'commits'
    command: "$HOME/.local/bin/commitcraft -w {{ .SelectedCommit.Sha }}"
    description: 'Reword selected commit with CommitCraft'
    output: terminal
  - key: 'T'
    context: 'commits'
    command: "$HOME/dotfiles/tools/lazygit-gretime.sh {{ .SelectedCommit.Sha }}"
    description: 'Rewrite the date of the selected commit (gretime)'
    output: terminal
  - key: 'H'
    context: 'commits'
    command: "hunk show {{ .SelectedCommit.Sha }}"
    description: 'Show the diff of the selected commit (hunk show)'
    output: terminal
