theme = "tokyonight"

[editor]
line-number = "relative"
# end-of-line-diagnostics = "hint"

# [editor.inline-diagnostics]
# cursor-line="error"
[editor.cursor-shape]
insert = "bar"
select = "underline" 


[keys.normal]
y = "yank_to_clipboard"
space.y = "yank"
space.p = "paste_after"
p = "paste_clipboard_after"
C-d = "kill_to_line_end"
tab = "indent"
S-tab = "unindent"
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
Cmd-c = "copy_selection_on_prev_line"

[keys.insert]
C-left = "goto_line_start"
C-right = "goto_line_end_newline"
C-v = "select_mode"
S-tab = "unindent"
