theme = "tokyonight"

[editor]
line-number = "relative"
# end-of-line-diagnostics = "hint"

# [editor.inline-diagnostics]
# cursor-line="error"
[editor.cursor-shape]
insert = "bar"
select = "underline" 


[keys.normal]
y = "yank_joined_to_clipboard"
space.y = "yank"
space.p = "paste_after"
p = "paste_clipboard_after"

[keys.insert]
C-left = "goto_line_start"
C-right = "goto_line_end_newline"
C-v = "select_mode"
