[changelog]
  bump_strategy = "patch"
  enabled = false
  path = "CHANGELOG.md"
  prompt_file = "prompts/changelog_refiner.prompt"
  prompt_model = "llama-3.3-70b-versatile"

[commit_format]
  type_format = "[%s]"

[commit_types]
  behavior = "replace"

  [[commit_types.types]]
    Color = "39"
    description = "Improvements to the implementation"
    tag = "IMP"

  [[commit_types.types]]
    Color = "197"
    description = "Bug fixes"
    tag = "FIX"

  [[commit_types.types]]
    Color = "47"
    description = "Feature additions"
    tag = "ADD"

  [[commit_types.types]]
    Color = "202"
    description = "Feature removals"
    tag = "REM"

  [[commit_types.types]]
    Color = "141"
    description = "Code refactoring"
    tag = "REF"

  [[commit_types.types]]
    Color = "221"
    description = "File moves or renames"
    tag = "MOV"

  [[commit_types.types]]
    Color = "81"
    description = "Release-related commits"
    tag = "REL"

  [[commit_types.types]]
    Color = "15"
    description = "Work in progress"
    tag = "WIP"

  [[commit_types.types]]
    Color = "254"
    description = "Documentation updates"
    tag = "DOC"

[prompts]
  change_analyzer_max_diff_size = 80000
  change_analyzer_prompt_file = "prompts/change_analyzer.prompt"
  change_analyzer_prompt_model = "meta-llama/llama-4-scout-17b-16e-instruct"
  commit_body_generator_prompt_file = "prompts/commit_body_generator.prompt"
  commit_body_generator_prompt_model = "openai/gpt-oss-120b"
  commit_title_generator_prompt_file = "prompts/commit_title_generator.prompt"
  commit_title_generator_prompt_model = "openai/gpt-oss-20b"
  only_translate_prompt_file = "prompts/only_translate.prompt"
  only_translate_prompt_model = "llama-3.1-8b-instant"
  release_body_prompt_file = "prompts/release_body.prompt"
  release_body_prompt_model = "openai/gpt-oss-120b"
  release_title_prompt_file = "prompts/release_title.prompt"
  release_title_prompt_model = "openai/gpt-oss-20b"
  release_refine_prompt_file = "prompts/release_refine.prompt"
  release_refine_prompt_model = "llama-3.3-70b-versatile"

[tui]
  theme = "harmonized"
  use_nerd_fonts = true

[agent]
  mode = "delegate"
  strategy = "single"
