version = 3
final_space = true

[palette]
  blue = '#8CAAEE'
  closer = 'p:os'
  error = '#FF0000'
  green = '#81ff91'
  lavender = '#87FF63'
  os = '#ACB0BE'
  pink = '#F4B8E4'
  success = '#00FF00'
  warning = '#FFFF00'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:pink'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:error{{end}}', '{{if eq .Code 0}}p:success{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    background = 'transparent'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '.. ..'
      home_icon = '~'
      max_depth = 3
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .Output }} '
    foreground = '#FFEB3B'
    background = 'transparent'
    type = 'command'
    style = 'plain'
    foreground_templates = [
        '{{if eq .Output ""}}p:blue{{end}}',  # Red for changes
        '{{if eq .Output ""}}p:error{{end}}'   # Green for up to date
      ]
    [blocks.segments.properties]
      command = '$HOME/dotfiles/scripts/check_dotfiles_status.sh'
      cache_duration = '1s'

  [[blocks.segments]]
    template = 'on {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{else}}p:lavender{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FB{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:error{{end}}', '{{if eq .Code 0}}p:success{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    template = 'on 󰅭 {{.Name}}'
    type = 'shell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#cc7eda> | with</> {{ .UserName }}@{{ .HostName }}'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if .Root}}p:warning{{else}}p:green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#cc7eda> | </><#7eb8da></> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#81ff91'
    background = 'transparent'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = true

  [[blocks.segments]]
    template = '<#cc7eda> | </><#7eb8da></> {{ .Full }}'
    foreground = '#81ff91'
    background = 'transparent'
    type = 'php'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#cc7eda> | </><#7eb8da> </> {{ .Full }}'
    foreground = '#81ff91'
    background = 'transparent'
    type = 'npm'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<> </>'
    foreground = '#81ff91'
    background = 'transparent'
    type = 'sysinfo'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#FFFF00>| Took {{ .FormattedMs }} 󰀡  </>'
    foreground = '#FFFFFF'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 150.0

  [[blocks.segments]]
    template = 'at {{ .CurrentDate | date .Format }}  <#cc7eda></>'
    foreground = '#FFFFFF'
    background = 'transparent'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '15:04:05'
