---
- name: Clone fzf repository
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '~/.fzf'
    version: 'master'
    depth: 1
  when: fzf_installed.rc != 0

- name: Install fzf
  command: '~/.fzf/install --all'
  args:
    executable: /bin/bash
  when: fzf_installed.rc != 0
