---
- name: Check if fzf is installed
  command: fzf --version
  register: fzf_installed
  ignore_errors: true
  changed_when: false


- name: Include install tasks based on OS
  include_tasks: "{{ os_family }}.yml"