---
- name: Check if fzf is installed
  command: fzf --version
  register: fzf_installed
  ignore_errors: true
  changed_when: false

- name: Include install tasks based on darwin
  include_tasks: "darwin.yml"
  when: ansible_os_family == "Darwin"

- name: Include install tasks based on linux distributions
  include_tasks: "linux.yml"
  when: ansible_os_family == "amazon" or ansible_os_family == "debian"