---
- name: Install bat on Debian-based systems
  apt:
    name: bat
    state: present
  when: bat_installed.rc != 0

- name: Create the symbolic link
  shell: |
    if ! command -v bat &> /dev/null; then
      mkdir -p ~/.local/bin
      ln -s /usr/bin/batcat ~/.local/bin/bat
    fi
  when: bat_installed.rc != 0
