- name: Check if Bat is installed
  command: bat --version
  register: bat_installed
  ignore_errors: true
  changed_when: false

- name: Install Bat based on OS
  include_tasks: "{{ os_family }}.yml"

- name: Common tasks
  include_tasks: "{{ os_family }}.yml"