---
- name: Check if docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false


- name: Install Docker based on OS
  include_tasks: "{{ os_family }}.yml"