---
- name: DotFiles Config
  hosts: local
  gather_facts: yes
  roles:
    - role: bat
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: config
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: delta
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: docker
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: fzf
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: oh-my-posh
      vars:
        os_family: "{{ ansible_os_family | lower }}"
        os_architecture: "{{ ansible_architecture | lower }}"
    - role: stow
      vars:
        os_family: "{{ ansible_os_family | lower }}"
    - role: zsh
      vars:
        os_family: "{{ ansible_os_family | lower }}"