---
- name: Check if oh-my-posh is installed
  command: oh-my-posh --version
  register: posh_installed
  ignore_errors: true
  changed_when: false

- name: Install oh-my-posh based on OS
  include_tasks: "{{ os_family }}.yml"
  when: posh_installed.rc != 0